<?php
session_start();
require_once "../auth/session_timeout.php";
require_once "../config/db.php";

if (!isset($_SESSION['user_id']) || $_SERVER['REQUEST_METHOD'] !== 'POST') {
    header("Location: reports.php"); exit();
}

$report_type = $_POST['report_type'] ?? '';
$start_date  = $_POST['start_date']  ?? '';
$end_date    = $_POST['end_date']    ?? '';

$results = null;

if ($report_type === 'booking') {
    $stmt = $conn->prepare("SELECT b.booking_id, f.facility_name, b.booking_date, b.time_slot, b.booking_status
                            FROM bookings b
                            JOIN facilities f ON b.facility_id = f.facility_id
                            WHERE b.booking_date BETWEEN ? AND ?");
    $stmt->bind_param("ss", $start_date, $end_date);

} elseif ($report_type === 'payment') {
    $stmt = $conn->prepare("SELECT payment_id, booking_id, amount, payment_method, payment_status
                            FROM payments
                            WHERE payment_date BETWEEN ? AND ?");
    $stmt->bind_param("ss", $start_date, $end_date);

} elseif ($report_type === 'facility') {
    $stmt = $conn->prepare("SELECT f.facility_name, COUNT(b.booking_id) AS total_usage
                            FROM bookings b
                            JOIN facilities f ON b.facility_id = f.facility_id
                            GROUP BY f.facility_name");
}

if (isset($stmt)) {
    $stmt->execute();
    $results = $stmt->get_result()->fetch_all(MYSQLI_ASSOC);
}

$type_label = match($report_type) {
    'booking'  => 'Booking Report',
    'payment'  => 'Payment Report',
    'facility' => 'Facility Usage Report',
    default    => 'Report'
};

date_default_timezone_set('Asia/Kuala_Lumpur');
$generated_by = $_SESSION['name'] ?? 'Admin';
$generated_at = date('F d, Y · h:i A');
$date_range   = date('M d, Y', strtotime($start_date)) . ' — ' . date('M d, Y', strtotime($end_date));

// Helper function to condense time slots into a single range

function condenseTimeSlots($time_slot_string) {
    if (empty($time_slot_string)) return '—';
    
    // Split the slots by comma and clean up whitespace
    $slots = array_map('trim', explode(',', $time_slot_string));
    
    if (count($slots) <= 1) {
        return $time_slot_string; // No need to condense if it's just 1 hour
    }
    
    $all_times = [];
    foreach ($slots as $slot) {
        // Split individual slot "08:00 - 09:00" into start and end times
        $parts = array_map('trim', explode('-', $slot));
        if (count($parts) === 2) {
            $all_times[] = $parts[0];
            $all_times[] = $parts[1];
        }
    }
    
    if (empty($all_times)) return $time_slot_string;
    
    // Sort times sequentially to find the true earliest start and latest end
    sort($all_times);
    
    $startTime = reset($all_times);
    $endTime = end($all_times);
    
    return $startTime . ' - ' . $endTime;
}
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title><?= $type_label ?> – Beerta Daarusalaam</title>
        <link rel="stylesheet" href="../assets/css/print_report.css" >
        
    </head>
    <body>

        <!-- Action bar (hidden on print) -->
        <div class="print-bar">
            <a href="reports.php" class="btn-close">← Back</a>
            <button class="btn-do-print" onclick="window.print()">🖨️ Print / Save as PDF</button>
        </div>

        <div class="print-wrap">

            <!-- Header -->
            <div class="report-header">
                <div class="logo-title">
                    <div class="logo-wrap">
                        <img src="../assets/logo_bd.png" alt="Logo">
                    </div>
                    <span class="brand-name">Beerta <span>Daarusalaam</span></span>
                </div>
                <div class="report-title"><?= $type_label ?></div>
                <div class="report-meta">
                    <div class="meta-item">
                        <strong>Date Range</strong>
                        <?= $date_range ?>
                    </div>
                    <div class="meta-item">
                        <strong>Generated By</strong>
                        <?= htmlspecialchars($generated_by) ?>
                    </div>
                    <div class="meta-item">
                        <strong>Generated At</strong>
                        <?= $generated_at ?>
                    </div>
                    <div class="meta-item">
                        <strong>Total Records</strong>
                        <?= count($results ?? []) ?>
                    </div>
                </div>
            </div>

            <!-- Body -->
            <div class="report-body">

                <?php if (!empty($results)): ?>

                    <!-- Summary boxes -->
                    <div class="summary-row">
                        <div class="summary-box">
                            <div class="summary-num"><?= count($results) ?></div>
                            <div class="summary-label">Total Records</div>
                        </div>

                        <?php if ($report_type === 'payment'): ?>
                            <?php $total_amount = array_sum(array_column($results, 'amount')); ?>
                            <div class="summary-box">
                                <div class="summary-num"> $ <?= number_format($total_amount, 2) ?></div>
                                <div class="summary-label">Total Amount</div>
                            </div>
                            <?php $paid_count = count(array_filter($results, fn($r) => strtolower($r['payment_status']) === 'verified')); ?>
                            <div class="summary-box">
                                <div class="summary-num"> $ <?= number_format(array_sum(array_column(array_filter($results, fn($r) => strtolower($r['payment_status']) === 'verified'), 'amount'))  , 2) ?></div>
                                <div class="summary-label">Paid</div>
                            </div>

                        <?php elseif ($report_type === 'booking'): ?>
                            <?php $confirmed = count(array_filter($results, fn($r) => strtolower($r['booking_status']) === 'confirmed')); ?>
                            <div class="summary-box">
                                <div class="summary-num"><?= $confirmed ?></div>
                                <div class="summary-label">Confirmed</div>
                            </div>
                            <?php $pending = count(array_filter($results, fn($r) => strtolower($r['booking_status']) === 'pending')); ?>
                            <div class="summary-box">
                                <div class="summary-num"><?= $pending ?></div>
                                <div class="summary-label">Pending</div>
                            </div>

                        <?php elseif ($report_type === 'facility'): ?>
                            <?php $total_usage = array_sum(array_column($results, 'total_usage')); ?>
                            <div class="summary-box">
                                <div class="summary-num"><?= $total_usage ?></div>
                                <div class="summary-label">Total Bookings</div>
                            </div>
                        <?php endif; ?>
                    </div>

                    <!-- Table -->
                    <table>
                        <thead>
                            <tr>
                                <?php if ($report_type === 'booking'): ?>
                                    <th>#</th><th>Facility</th><th>Date</th><th>Time Slot</th><th>Status</th>
                                <?php elseif ($report_type === 'payment'): ?>
                                    <th>Pay ID</th><th>Booking ID</th><th>Amount</th><th>Method</th><th>Status</th>
                                <?php else: ?>
                                    <th>Facility</th><th>Total Bookings</th><th>Usage</th>
                                <?php endif; ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php
                            $max_usage = $report_type === 'facility' ? max(array_column($results, 'total_usage') ?: [1]) : 1;
                            foreach ($results as $row):
                            ?>
                            <tr>
                                <?php if ($report_type === 'booking'): ?>
                                    <td class="id-cell">#<?= $row['booking_id'] ?></td>
                                    <td><?= htmlspecialchars($row['facility_name']) ?></td>
                                    <td><?= date('M d, Y', strtotime($row['booking_date'])) ?></td>
                                    <td><?= htmlspecialchars(condenseTimeSlots($row['time_slot'])) ?></td>
                                    <td><span class="badge badge-<?= strtolower($row['booking_status']) ?>"><?= $row['booking_status'] ?></span></td>

                                <?php elseif ($report_type === 'payment'): ?>
                                    <td class="id-cell">#<?= $row['payment_id'] ?></td>
                                    <td class="id-cell">#<?= $row['booking_id'] ?></td>
                                    <td class="amount-cell"> $ <?= number_format($row['amount'], 2) ?></td>
                                    <td><?= htmlspecialchars($row['payment_method']) ?></td>
                                    <td><span class="badge badge-<?= strtolower($row['payment_status']) ?>"><?= $row['payment_status'] ?></span></td>

                                <?php else: ?>
                                    <td><?= htmlspecialchars($row['facility_name']) ?></td>
                                    <td><?= $row['total_usage'] ?></td>
                                    <td>
                                        <div class="usage-bar-wrap">
                                            <div class="usage-bar-bg">
                                                <div class="usage-bar-fill" style="width:<?= round(($row['total_usage'] / $max_usage) * 100) ?>%"></div>
                                            </div>
                                        </div>
                                    </td>
                                <?php endif; ?>
                            </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>

                <?php else: ?>
                    <div class="no-data">
                        <i>📭</i>
                        <p>No data found for the selected range.</p>
                    </div>
                <?php endif; ?>

            </div>

            <!-- Footer -->
            <div class="report-footer">
                <span>Beerta Daarusalaam Sports Facility System</span>
                <span>Generated: <?= $generated_at ?></span>
            </div>

        </div>

        <script>
            window.onload = () => window.print();
        </script>
    </body>
</html>